[tools]
bat="latest"
eza="latest"
gh="latest"
"github:anomalyco/opencode" = "latest"
jj="latest"
jjui="latest"
jq="latest"
ripgrep="latest"

[settings]
quiet = false

[settings.github]
credential_command = "op read 'op://Private/Mise PAT/token'"