[".local/share/chezmoi/chezmoi/.chezmoitemplates/user-js-updater.sh"]
  type = "file"
  url = "https://github.com/arkenfox/user.js/raw/master/updater.sh"
  refreshPeriod = "168h"
[".gnupg/github_web.gpg"]
  type = "file"
  url = "https://github.com/web-flow.gpg"
  refreshPeriod = "168h"