#!/usr/bin/env bash
#
set -euo pipefail

if ! chezmoi="$(command -v chezmoi)"; then
	bin_dir="${HOME}/.local/bin"
	chezmoi="${bin_dir}/chezmoi"
	echo "Installing chezmoi to '${chezmoi}'" >&2
	if command -v curl >/dev/null; then
		# chezmoi_install_script="$(curl -fsSL get.chezmoi.io)"
		# Workaround until get.chezmoi.io is updated to use the script from https://github.com/twpayne/chezmoi/issues/4303
		chezmoi_install_script="$(curl -fsSL https://raw.githubusercontent.com/twpayne/chezmoi/4406bd873ca0c04f0e8a7e306dd52a71d9ae2f19/assets/scripts/install.sh)"
	elif command -v wget >/dev/null; then
		chezmoi_install_script="$(wget -qO- get.chezmoi.io)"
	else
		echo "To install chezmoi, you must have curl or wget installed." >&2
		exit 1
	fi
	sh -c "${chezmoi_install_script}" -- -b "${bin_dir}"
	unset chezmoi_install_script bin_dir
fi

# POSIX way to get script's dir: https://stackoverflow.com/a/29834779/12156188
script_dir="$(cd -P -- "$(dirname -- "$(command -v -- "$0")")/../" && pwd -P)"

set -- init --apply --source="${script_dir}"

echo "Running 'chezmoi $*'" >&2
# exec: replace current process with chezmoi
exec "$chezmoi" "$@"
