#!/bin/sh
# Run in codespaces after starting

# Always want to use ZSH as my default shell (e.g. for SSH)
sudo="sudo"
if [ "${USER}" = "root" ]; then
  sudo=""
fi

if ! grep -q "${USER}.*/bin/zsh" /etc/passwd; then
  $sudo chsh -s /bin/zsh "${USER}"
fi

# Install some developer tools and setup Linux how I like it
if [ "$(command -v rg)" = "" ]; then
  $sudo apt-get install -y bat bfs exa grc ripgrep
fi

echo "machine goproxy.githubapp.com login nobody password $GITHUB_TOKEN" >> "$HOME/.netrc"
