#!/bin/sh
# Run in codespaces after starting
echo "==> Running codespaces post-start script"

# Always want to use ZSH as my default shell (e.g. for SSH)
sudo="sudo"
if [ "${USER}" = "root" ]; then
  sudo=""
fi

if ! grep -q "${USER}.*/bin/zsh" /etc/passwd; then
  $sudo chsh -s /bin/zsh "${USER}"
fi

# Install some developer tools and setup Linux how I like it
if [ "$(command -v rg)" = "" ]; then
  $sudo apt-get -q update && $sudo apt-get -q install -y ripgrep most gh
fi

if [ ! -f "${HOME}/.netrc" ] || grep -vq "goproxy.githubapp.com" "${HOME}/.netrc"; then
  echo "machine goproxy.githubapp.com login nobody password $GITHUB_TOKEN" >> "$HOME/.netrc"
fi