#!/bin/sh
# Run in codespaces after starting
echo "==> Running codespaces post-start script"

# Always want to use ZSH as my default shell (e.g. for SSH)
sudo="sudo"
if [ "${USER}" = "root" ]; then
  sudo=""
fi

if ! grep -q "${USER}.*/bin/zsh" /etc/passwd; then
  $sudo chsh -s /bin/zsh "${USER}"
fi

# Install some developer tools and setup Linux how I like it
if [ "$(command -v rg)" = "" ]; then
  $sudo apt-get install -y -o Dpkg::Options::="--force-overwrite" bat bfs grc ripgrep
fi

# If the workspace contains Ruby files, install my default gems
if [ "$(find . -maxdepth 2 -name '*.rb' | wc -l)" -gt 0 ]; then
  # shellcheck disable=SC2046
  gem install $(cat "$HOME/.config/asdf/default-gems")
fi

echo "machine goproxy.githubapp.com login nobody password $GITHUB_TOKEN" >> "$HOME/.netrc"
