import = [ "~/.config/alacritty/theme.toml" ]

[font]
size = 12
normal = { family = "JetBrainsMono NF", style = "Regular" }
bold = { family = "JetBrainsMono NF", style = "Bold" }
italic = { family = "JetBrainsMono NF", style = "Italic" }

[env]
TERM = "xterm-256color"

[shell]
program = "/opt/homebrew/bin/zellij"

[window]
#padding.x = 5
#padding.y = 5
dynamic_padding = true
#decorations = "none"
opacity = 0.97
dimensions = { columns = 180, lines = 60 }
option_as_alt = "OnlyLeft"

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]